version: '3'

services:
  ingress:
    image: traefik:1.7-alpine 
    container_name: ingress
    command: -c /etc/traefik/traefik.toml
    ports:
      - "8080:8080" # Dashboard port
    volumes:
      - ./conf/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres
    container_name: db
    environment: 
      - "POSTGRES_USER=www_user"
      - "POSTGRES_PASSWORD=www_passwrd"
      - "POSTGRES_DB=maindb"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
  roachdb:
    image: cockroachdb/cockroach
    container_name: roachdb
    command: start --insecure --listen-addr=roachdb:26257
    volumes:
      - roachdata:/cockroach
    ports: 
      - "26257"
  message-bus:
    image: "rabbitmq:3.7-management-alpine"
    container_name: message-bus
    labels:
      - "traefik.domain=mg-rast.local"
      - "traefik.backend=message-bus_admin"
      - "traefik.enable=true"
    volumes:
      - ./conf/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitdata:/var/lib/rabbitmq
    ports:
      - "8888:15672" # Admin UI port
      - "5672"
  web:
    build: .
    container_name: web
    command: start
    labels:
      - "traefik.domain=mg-rast.local"
      - "traefik.backend=web"
      - "traefik.enable=true"
    volumes:
      - .:/usr/src/app
    ports:
      - "80:8000"
    depends_on:
      - db
      - message-bus

volumes: 
  pgdata:
  rabbitdata:
  roachdata: