FROM python:3.7-alpine3.9
ENV PYTHONUNBUFFERED 1
ENV LIBRARY_PATH=/lib:/usr/lib

COPY requirements.txt .

RUN apk update && apk add --no-cache --virtual .build-deps \
    build-base postgresql-dev mariadb-dev musl-dev  && \
    apk --no-cache add libpq libjpeg-turbo jpeg-dev zlib-dev py3-mysqlclient mysql-client postgresql-client && \
    pip3 install --no-cache-dir -r requirements.txt  && \
    apk --purge del .build-deps

ENTRYPOINT ["ash"]