# Generated by Django 2.1.7 on 2019-03-12 21:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('createdt', models.DateTimeField(auto_now_add=True, verbose_name='Creation datetime')),
                ('moddt', models.DateTimeField(auto_now=True, verbose_name='Last modified datetime')),
                ('description', django.contrib.postgres.fields.jsonb.JSONField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
