FROM python:3.7-alpine3.9
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/base
COPY . .

RUN apk add --allow-untrusted apk/py3-psycopg2* apk/postgresql-client*; \
    apk add --virtual .build-deps apk/gcc* apk/musl-dev* apk/postgresql-libs* apk/postgresql-dev*; \
    pip install wheels/*.whl --no-cache-dir; \
    pip install -r requirements.txt --no-cache-dir; \
    apk --purge del .build-deps